### ISSUE TITLE
v1.3.0 has no prebuilt binaries for windows/arm64 and darwin/arm64

### ISSUE THREAD

**Issue by suzuki-shunsuke** [makew0rld/didder#16]
v1.2.0 has prebuilt binaries for windows/arm64 and darwin/arm64

https://github.com/makew0rld/didder/releases/tag/v1.2.0

- [didder_1.2.0_macOS_arm64](https://github.com/makew0rld/didder/releases/download/v1.2.0/didder_1.2.0_macOS_arm64)
- [didder_1.2.0_windows_arm64.exe](https://github.com/makew0rld/didder/releases/download/v1.2.0/didder_1.2.0_windows_arm64.exe)

<img width="324" alt="image" src="https://github.com/makew0rld/didder/assets/13323303/b9293aa1-ce19-4bea-8b8a-6be680c3ea56">

On the other hand, v1.3.0 doesn't.

https://github.com/makew0rld/didder/releases/tag/v1.3.0

<img width="334" alt="image" src="https://github.com/makew0rld/didder/assets/13323303/e0284a28-dc37-4cd9-a4f8-19b3f5128a84">

**Comment by suzuki-shunsuke** [comment]
I'll send a pull request to resolve the issue soon.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/makew0rld/didder/pull/17

**Comment by suzuki-shunsuke** [comment]
https://github.com/makew0rld/didder/actions/runs/7279880843/job/19837113260#step:4:32

```
         • DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```

- https://goreleaser.com/deprecations/#builds-for-windowsarm64
- https://goreleaser.com/deprecations/#builds-for-darwinarm64

GoReleaser version is old.

https://github.com/makew0rld/didder/blob/409cfa6ce70d15a9c70ce3783e0d362e1cafdf4e/.github/workflows/goreleaser.yml#L20-L23

We should upgrade GoReleaser to v1, then the issue would be resolved.

**Comment by makew0rld** [comment]
I will manually upload these two builds so they exist for v1.3.0.

**Comment by suzuki-shunsuke** [comment]
@makew0rld Versions are wrong. Not 1.2.0 but 1.3.0.
https://github.com/makew0rld/didder/releases/tag/v1.3.0

<img width="329" alt="image" src="https://github.com/makew0rld/didder/assets/13323303/6db22315-5e9e-44cd-a637-42705acdf9a2">

**Comment by makew0rld** [comment]
Whoops, fixed now. Thanks.

**Comment by suzuki-shunsuke** [comment]
@makew0rld
Thank you!
Sorry to bother you, but I really appreciate it if you update the checksum file too to add checksums of windows/arm64 and darwin/arm64.

[didder_1.3.0_checksums.txt](https://github.com/makew0rld/didder/releases/download/v1.3.0/didder_1.3.0_checksums.txt)

**Comment by makew0rld** [comment]
Ok fair enough, I've updated it.

**Comment by suzuki-shunsuke** [comment]
Thank you!

**Comment by sergeevabc** [comment]
Err… It seems you've compiled windows binaries with too bleeding-edge Go which is incompatible with Windows 7. It causes a crash. Please, consider recompiling.

``` console
$ didder --palette "black white" -i in.png -o out.png bayer 16x16
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46b195
rax     0x0
rbx     0x7fb800
rcx     0x84e940
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x820978
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x7fb1a0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by suzuki-shunsuke** [comment]
I'm not a maintainer of this project, but Microsoft ended Windows 7 support on January 14, 2020.

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

So I don't think we need to support Windows 7 anymore.
Again, I'm not a maintainer of this project. This is just my opinion.

**Comment by sergeevabc** [comment]
@suzuki-shunsuke, this app, Didder, deals with the degradation of images to the graphics level of computers on [cassettes](https://en.wikipedia.org/wiki/ZX_Spectrum) and of [handheld](https://en.wikipedia.org/wiki/Game_Boy) game consoles, which you probably didn't even catch, but I did. Isn't it absurd to require the latest OS for the sake of this conversion? Windows 7 has all the necessary arithmetic apparatus so that the formulas embedded in Didder still work. [ImageMagick](https://en.wikipedia.org/wiki/ImageMagick) and [VIPS](https://en.wikipedia.org/wiki/VIPS_(software)) work here.

The developers of Go language want to look dandy, to shake hands with the <strike>devils</strike> hegemons of the Silicon Valley, whereas I want apps to be future-proof. Think UNIX apps that are built to last across OSes without “do not touch after we're gone” fear-mongering. Microsoft is a business enterprise, they refuse to support this or that for reasons of profit and nothing else. They're forcing users to switch to the software-as-a-service (SaaS) model by means of [artificial obsolescence](https://en.wikipedia.org/wiki/Planned_obsolescence), because it's profitable, not because it's the right step forward for our civilization. Do they offer any breakthroughs as before (think NTFS over FAT32, for example)? No, they roll out poorly coded, spying Windows 10-11-12+ and then calm your anxiety with a weekly dose of patches. This is a drug dealer-addict relationship, not a progress.

**Comment by suzuki-shunsuke** [comment]
I see. Thank you for your explanation.
I don't have a strong opinion, so I'll leave it to you and maintainers.

**Comment by makew0rld** [comment]
I have no interest in supporting OSes not supported by the latest Go compiler. Of course you are always able to compile from source with whatever compiler versions you wish.
